### ISSUE TITLE
Plis add stereo support.

### ISSUE THREAD

**Issue by Hats15** [somewhatlurker/DivaSound#4]
Hi boy, could you go back to stereo mode? since the game worked with sound in that mode or in your case, you could pass version 1.8 of the diva loader that included that mode 'I would appreciate it a lot

**Comment by somewhatlurker** [comment]
It looks like this issue isn't actually with DivaSound. Instead it's an issue that should be resolved by DIVA Loader.  
Alternatively, you should be able to get sound working if you copy the files from DivaSound.zip (on the "releases" page) into your plugins folder.

I understand that this is a less than ideal response due to old versions of DIVA Loader being unavailable, but I don't feel it's appropriate to support DIVA Loader here currently.
